name: .NET POI workflow test

on:
  workflow_dispatch:
  push:
    paths: /apis/poi/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.202
      - name: Install dependencies
        run: dotnet restore ./apis/poi/web/poi.csproj
      - name: Build  
        run: dotnet build --configuration Release --no-restore ./apis/poi/web/poi.csproj
      - name: Test
        run: dotnet test --no-restore --verbosity normal
