name: .NET POI workflow test

on:
  workflow_dispatch:
  push:
    paths: 
      - /apis/poi/**
      - .github/workflows/dotnetPOITEST.yml
      
  pull_request:
    branches: main
    paths: 
      - /apis/poi/**
      - .github/workflows/dotnetPOITEST.yml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.202
      - name: Install dependencies
        run: dotnet restore ./apis/poi/web/poi.csproj
      - name: Build  
        run: dotnet build --configuration Release --no-restore ./apis/poi/web/poi.csproj
      - name: Test
        run: dotnet test --no-restore --verbosity normal ./apis/poi/tests/UnitTests/UnitTests.csproj       
      - name: Open New GitHub Issue
        # You may pin to the exact commit or the version. test
        # uses: fullStackMiller/open-issue@e85fe8f3a4b39e8270d9846a727ec0b2d95e9252        
        uses: fullStackMiller/open-issue@v1.0.1
        if: ${{ failure() }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Build failure
          body: ${{ github.run_number }}
          assignees: rrohit-singh
       
      
      
