name: .NET POI workflow test

env: 
  docker_path: ./apis/poi/web/
  repository: devopsoh/api-poi
  registry: openhacknsg2j8q8acr.azurecr.io
  AZURE_WEBAPP_NAME: openhacknsg2j8q8poi
  staging-url: http://openhacknsg2j8q8poi-staging.azurewebsites.net/api/healthcheck/poi

on:
  workflow_dispatch:
  push:
    paths: 
      - /apis/poi/**
      - .github/workflows/dotnetPOITEST.yml
      
  pull_request:
    branches: main
    paths: 
      - /apis/poi/**
      - .github/workflows/dotnetPOITEST.yml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.202
      - name: Install dependencies
        run: dotnet restore ./apis/poi/web/poi.csproj
      - name: Build  
        run: dotnet build --configuration Release --no-restore ./apis/poi/web/poi.csproj
      - name: Test
        run: dotnet test --no-restore --verbosity normal ./apis/poi/tests/UnitTests/UnitTests.csproj       
      - name: Open New GitHub Issue
        # You may pin to the exact commit or the version. test
        # uses: fullStackMiller/open-issue@e85fe8f3a4b39e8270d9846a727ec0b2d95e9252        
        uses: fullStackMiller/open-issue@v1.0.1
        if: ${{ failure() }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Build failure
          body: ${{ github.run_number }}
          assignees: rrohit-singh
    
  buildDocker:
      runs-on: ubuntu-latest
      
      steps:

        - uses: actions/checkout@v2
 
        - name: Docker login    
          run: docker login $registry -u ${{ secrets.ACR_USER }} -p ${{ secrets.ACR_KEY }}
 
        - name: Docker build
          run: docker build -t $registry/$repository:${{github.run_number}} --build-arg build_version=${{github.run_number}} $docker_path
 
        - name: Docker Push
          run: docker push $registry/$repository:${{github.run_number}}
  deploy-staging:
      runs-on: ubuntu-latest
      needs: [build, buildDocker]
      steps: 
        - uses: actions/checkout@v2
        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@0b651ed7546ecfc75024011f76944cb9b381ef1e
          with:
            app-name: ${{ env.AZURE_WEBAPP_NAME }}
            publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_STAGING }}
            images: ${{env.registry}}/${{env.repository}}:${{github.run_number}}
        - name: Verify staging slot
          run: apis/poi/wait-for-endpoint.sh ${{env.staging-url}}​​​​​ -t 30
      
      

